server:
  port: 80
spring:
  application:
    name: web-gateway
eureka:
  client:
    service-url: # 一般最好从Eureka 服务端的配置文件复制, 客户端与服务端必须一致
      defaultZone: http://127.0.0.1:9000/eureka/
    registry-fetch-interval-seconds: 5 # 每5S注册一次自己
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  routes:
    customer-service: # 可以自定义
      path: /customer/** # 转发路径规则
      serviceId: customer-service #必须是注册到Eureka的application.name
      strip-prefix: false
    routing-service: # 可以自定义
      path: /routing/** # 转发路径规则
      serviceId: routing-service #必须是注册到Eureka的application.name
      strip-prefix: false
    order-service: # 可以自定义
      path: /order/** # 转发路径规则
      serviceId: order-service #必须是注册到Eureka的application.name
      strip-prefix: false
    sms-service: # 可以自定义
      path: /sms/** # 转发路径规则
      serviceId: sms-service #必须是注册到Eureka的application.name
      strip-prefix: false
  prefix: /api #路由前缀
  retryable: true
  ribbon:
    ConnectTimeout: 250 # 连接超时时间(ms)
    ReadTimeout: 25000 # 通信超时时间(ms)
    OkToRetryOnAllOperations: true # 是否对所有操作重试
    MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
    MaxAutoRetries: 0 # 同一实例的重试次数
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms