server:
  port: 9102
spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.241:3306/zyhk_master?serverTimezone=UTC
    username: root
    password: zyhk123
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  redis:
    host: 192.168.0.241
    password: zyhk237@123
    database: 4
    
eureka:
  client:
    service-url: # 一般最好从Eureka 服务端的配置文件复制, 客户端与服务端必须一致
      defaultZone: http://127.0.0.1:9000/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms